### ISSUE TITLE
[1.12 issue] Block display Waiting for server... message

### ISSUE THREAD

**Issue by dancc7t** [McJty/TheOneProbe#199]
Hi, i noticed that sometimes, especially when moving or flying at high speeds, a red message appears below the block name at the tooltip block info box, i could not record it myself but i found at someone else's video the same message.
[https://imgur.com/a/SQsEe](url)
I am playing SP but this message appears quite oftenly when i move fast with my quantumsuit.
For me this is not a big issue, although it would be better imo changing the message color from red to white so it is less noticeable.

**Comment by McJty** [comment]
Note that even in SP there is a (builtin) server that runs. Anyway I could change the color of the message (or make it configurable)

**Comment by dancc7t** [comment]
Thanks for the quick response, yeah, that would be better.

**Comment by beesyndicate** [comment]
Hello on multiplayer server that I have put theoneprobe .jar file on and restarted the server I still get a constant message "waiting for server" on the one probe display. It never updates.
![1](https://user-images.githubusercontent.com/32340677/30971028-d5b7d968-a434-11e7-998d-75d8a8fa3b43.png)

**Comment by McJty** [comment]
Same version of the one probe on server and client? What is the exact version?

**Comment by beesyndicate** [comment]
NM this was caused by a forge configuration problem. I have fixed it and it is working correctly now TY soooo much !

**Comment by chuk1994** [comment]
Hi im having the same issue, how did you resolve this problem?

**Comment by fbartho** [comment]
I'm exhibiting this issue on a brand new Minecraft server using the latest SpigotMC / Forge versions. -- I verified I have the latest TOP jar running on both server and client & double checked the md5 with the expected md5 from the site.

@beesyndicate would you mind explaining what the config problem was?
@chuk1994 did you ever resolve this?

**Comment by ROOTBEEROFF** [comment]
This issue is still there in 1.16.5. Annoying since I will need to restart my server few time to actually remove the "Waiting for server..."
Normally it should show stats like if you have a machine with liquid or gas in it, it should show the amount of it

**Comment by McJty** [comment]
If TOP shows that it is waiting for server then that's not a problem with TOP. TOP is just showing that there is a problem with the server and that problem can be caused by anything. Like a bug in another mod which makes the server lag/stop

**Comment by ROOTBEEROFF** [comment]
But it will randomly work after few reboot, kinda weird.

**Comment by McJty** [comment]
yes but that doesn't imply it has to do with TOP does it? That just means that whatever other mod caused a problem will randomly not have that problem after reboot

**Comment by ROOTBEEROFF** [comment]
Hmm I see well I was thinking it was this mod issue, guess not and wont probably fix a solution since im playing on All The Mods 6

**Comment by McJty** [comment]
Note that it can also be caused by someone's base doing something very expensive or having tons of items on the ground. Basically the only thing TOP is doing is showing there is a problem with the server

**Comment by Kasia1403** [comment]
> NM this was caused by a forge configuration problem. I have fixed it and it is working correctly now TY soooo much !

How did You fix it ?
